### ISSUE TITLE
Make code pass flake8

### ISSUE THREAD

**Issue by bittner** [jpritcha3-14/shooting-game#1]
This is a pretty awesome game! What I've seen it does a lot, and I haven't seen much yet, I have just started playing it a few minutes ago.

To make it more accessible as a top-notch example for writing games, would you be willing to make the code pass the Python coding style checker [flake8](http://flake8.pycqa.org/en/latest/)? Currently, `flake8` reports 376 violations:

```bash
$ flake8 | wc -l
376
```

**Comment by jpritcha3-14** [comment]
Thanks for the suggestion 👍  I should definitely spend some time reviewing the style guide and this would be a great way to do that and fix up the code at the same time.  

Starting off there appear to be some call outs with flake8 that, while correct, go against common practice with pygame.  An example being: 
```python
from pygame.locals import *  # Global scope for pygame constants
```
I will use flake8 to help correct my many other egregious style violations and minimize the number detected.  I'll use my best judgment on gray areas and keep readability in mind 😄

**Comment by jpritcha3-14** [comment]
I ended up removing all non-compliances found by flake8 in the latest commit.

**Comment by bittner** [comment]
Awesome!
